name: smoke-ui-test-job

on:
  schedule:
    - cron: "*/60 8-23 * * *"

jobs:
  smoke-ui-test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i
    - name: Run Smoke Tests
      env:
        CYPRESS_SUPPLIER_PORTAL_URL_DEV: ${{ secrets.CYPRESS_SUPPLIER_PORTAL_URL_DEV }}
        CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
        CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
        CYPRESS_SUPPLIER_PORTAL_URL: ${{ secrets.CYPRESS_SUPPLIER_PORTAL_URL }}
        CYPRESS_RETAILTER_USER_EMAIL: ${{ secrets.CYPRESS_RETAILTER_USER_EMAIL }}
        CYPRESS_RETAILTER_USER_PASSWORD: ${{ secrets.CYPRESS_RETAILTER_USER_PASSWORD }}
      run: npm run smoke-test
    - run: npm run merge:reports
    - run: npm run create:html:report
    - name: Merge Cypress Reports
      if: always()
      run: npm run merge:reports
    - name: Generate HTML report
      if: always()
      run: npm run create:html:report
    - name: Save test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-reporter
        path: TestReport
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
        notification_title: '{workflow} has {status_message}'
        message_format: '{emoji} The E2E tests failed in *{workflow}* workflow in the <{repo_url}|{repo}> repository, you can check the report in the artifacts section in the bottom of the following link https://github.com/inventa-shop/qa-test-prod/actions/runs/${{ github.run_id }}'
        footer: 'Linked to Repo <{repo_url}|{repo}>'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}