name: smoke-ui-test-fp

on:
  schedule:
    - cron: "*/10 0-7 * * *"

jobs:
  smoke-ui-test-fp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i
    - run: npm run smoke-test-fp
    - name: Notify Slack
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
        notification_title: '{workflow} has {status_message}'
        message_format: '{emoji} The E2E tests failed in *{workflow}* workflow in the <{repo_url}|{repo}> repository, you can check the report in the artifacts section in the bottom of the following link https://github.com/inventa-shop/qa-test-prod/actions/runs/${{ github.run_id }}'
        footer: 'Linked to Repo <{repo_url}|{repo}>'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}