name: ui-test
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ui-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i
    - run: npm run alert
    - run: npm run merge:reports
    - run: npm run create:html:report
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
        notification_title: '{workflow} has {status_message}'
        message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
        footer: 'Linked to Repo <{repo_url}|{repo}>'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}